### ISSUE TITLE
Craft 5

### ISSUE THREAD

**Issue by wmdhosting** [PropelCog/order-import#2]
nay plans to bring this to 5

**Comment by christopherhealey** [comment]
@wmdhosting no plans of right now, will re-open if that changes so you get an update.

**Comment by bymayo** [comment]
@wmdhosting I released a plugin today that does the same as this one, but works with Craft 5 - https://github.com/bymayo/craft-order-importer

Hope I'm not stepping on @christopherhealey toes on this. But we needed this functionality for Craft 5 so had to build it!

**Comment by wmdhosting** [comment]
Great :)  just on time..  :)

I allready  "celebreted" on Discord :) 

Will buy soon :)

**Comment by bymayo** [comment]
@wmdhosting Any issues let me know! I am also on Discord.
